name: Continous Integration Johany

# El workflow se ejecuta al hacer push a la rama master
on:
  push:
    branches: [ "main" ,"master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: "Descarga" del código (Checkout)
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Ejecución de pruebas de calidad de código (Mock)
      - name: Pruebas de SAST
        run: echo "Ejecución de pruebas de SAST"

      # Paso 3: Crear el archivo de credenciales
      # Aquí usamos los secretos que creaste en el paso anterior
      - name: Crear archivo de credenciales
        run: |
          sed -e 's\${USERNAME}/${{ secrets.USERNAME }}/g' \
              -e 's\${PASSWORD}/${{ secrets.PASSWORD }}/g' \
              credentials.ini.tpl > credentials.ini

      # Paso 4: Construcción del container de Docker
      - name: Build docker image
        run: docker build -t devops_ws --tag devops_ws_:$(date +%s) .

      # Paso 5: Guardar el archivo generado como artefacto 
      - name: Upload credentials artifact
        uses: actions/upload-artifact@v4
        with:
          name: credentials-file
          path: credentials.ini